language: d
sudo: false

matrix:
  include:
    - d: dmd-2.089.0
    - d: dmd-2.088.1
    - d: dmd-2.087.1
    - d: ldc-1.18.0
    - d: ldc-1.17.0

script:
  - dub test --build=unittest-cov --compiler=${DC}
  - dub build --compiler=${DC}

after_success:
 - bash <(curl -s https://codecov.io/bash)
