name: CI
on: [push, pull_request]

jobs:
  test:
    name: Dub Test
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - windows-2022
          - macos-12
        dc:
          - dmd-2.109.1
          - dmd-2.099.1
          - ldc-1.40.0
          - ldc-1.29.0

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v2
        with:
          compiler: ${{ matrix.dc }}

      - name: Run tests
        run: dub test -q --build=unittest-cov-ctfe

      - name: Build binary
        run: dub build -q

      - uses: codecov/codecov-action@v5.1.2
