name: CI
on: [push, pull_request]

jobs:
  test:
    name: Dub Test
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019]
        dc: [dmd-2.098.1, ldc-1.28.1]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1.1.1
        with:
          compiler: ${{ matrix.dc }}

      - name: Run tests
        run: dub test -q --build=unittest-cov

      - name: Build binary
        run: dub build -q

      - uses: codecov/codecov-action@v2
